version: '3.9'

services:
  db:
    build: .
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
      MYSQL_USER: beer
      MYSQL_PASSWORD: beer
    ports:
      - "3309:3306"
